language: php

php:
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - composer self-update
  - composer update --prefer-source --no-interaction ${COMPOSER_FLAGS}

script: vendor/bin/phpunit
